//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.03 at 11:06:56 PM CEST 
//


package org.freedesktop.appstream.appdata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.freedesktop.appstream.appdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ComponentsComponentDescriptionUlLi_QNAME = new QName("", "li");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.freedesktop.appstream.appdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link Components.Component }
     * 
     */
    public Components.Component createComponentsComponent() {
        return new Components.Component();
    }

    /**
     * Create an instance of {@link Components.Component.Languages }
     * 
     */
    public Components.Component.Languages createComponentsComponentLanguages() {
        return new Components.Component.Languages();
    }

    /**
     * Create an instance of {@link Components.Component.ContentRating }
     * 
     */
    public Components.Component.ContentRating createComponentsComponentContentRating() {
        return new Components.Component.ContentRating();
    }

    /**
     * Create an instance of {@link Components.Component.Releases }
     * 
     */
    public Components.Component.Releases createComponentsComponentReleases() {
        return new Components.Component.Releases();
    }

    /**
     * Create an instance of {@link Components.Component.Releases.Release }
     * 
     */
    public Components.Component.Releases.Release createComponentsComponentReleasesRelease() {
        return new Components.Component.Releases.Release();
    }

    /**
     * Create an instance of {@link Components.Component.Screenshots }
     * 
     */
    public Components.Component.Screenshots createComponentsComponentScreenshots() {
        return new Components.Component.Screenshots();
    }

    /**
     * Create an instance of {@link Components.Component.Screenshots.Screenshot }
     * 
     */
    public Components.Component.Screenshots.Screenshot createComponentsComponentScreenshotsScreenshot() {
        return new Components.Component.Screenshots.Screenshot();
    }

    /**
     * Create an instance of {@link Components.Component.Keywords }
     * 
     */
    public Components.Component.Keywords createComponentsComponentKeywords() {
        return new Components.Component.Keywords();
    }

    /**
     * Create an instance of {@link Components.Component.Description }
     * 
     */
    public Components.Component.Description createComponentsComponentDescription() {
        return new Components.Component.Description();
    }

    /**
     * Create an instance of {@link Components.Component.Translation }
     * 
     */
    public Components.Component.Translation createComponentsComponentTranslation() {
        return new Components.Component.Translation();
    }

    /**
     * Create an instance of {@link Components.Component.Name }
     * 
     */
    public Components.Component.Name createComponentsComponentName() {
        return new Components.Component.Name();
    }

    /**
     * Create an instance of {@link Components.Component.Summary }
     * 
     */
    public Components.Component.Summary createComponentsComponentSummary() {
        return new Components.Component.Summary();
    }

    /**
     * Create an instance of {@link Components.Component.DeveloperName }
     * 
     */
    public Components.Component.DeveloperName createComponentsComponentDeveloperName() {
        return new Components.Component.DeveloperName();
    }

    /**
     * Create an instance of {@link Components.Component.Icon }
     * 
     */
    public Components.Component.Icon createComponentsComponentIcon() {
        return new Components.Component.Icon();
    }

    /**
     * Create an instance of {@link Components.Component.Categories }
     * 
     */
    public Components.Component.Categories createComponentsComponentCategories() {
        return new Components.Component.Categories();
    }

    /**
     * Create an instance of {@link Components.Component.Kudos }
     * 
     */
    public Components.Component.Kudos createComponentsComponentKudos() {
        return new Components.Component.Kudos();
    }

    /**
     * Create an instance of {@link Components.Component.Mimetypes }
     * 
     */
    public Components.Component.Mimetypes createComponentsComponentMimetypes() {
        return new Components.Component.Mimetypes();
    }

    /**
     * Create an instance of {@link Components.Component.Url }
     * 
     */
    public Components.Component.Url createComponentsComponentUrl() {
        return new Components.Component.Url();
    }

    /**
     * Create an instance of {@link Components.Component.Bundle }
     * 
     */
    public Components.Component.Bundle createComponentsComponentBundle() {
        return new Components.Component.Bundle();
    }

    /**
     * Create an instance of {@link Components.Component.Languages.Lang }
     * 
     */
    public Components.Component.Languages.Lang createComponentsComponentLanguagesLang() {
        return new Components.Component.Languages.Lang();
    }

    /**
     * Create an instance of {@link Components.Component.ContentRating.ContentAttribute }
     * 
     */
    public Components.Component.ContentRating.ContentAttribute createComponentsComponentContentRatingContentAttribute() {
        return new Components.Component.ContentRating.ContentAttribute();
    }

    /**
     * Create an instance of {@link Components.Component.Releases.Release.Description }
     * 
     */
    public Components.Component.Releases.Release.Description createComponentsComponentReleasesReleaseDescription() {
        return new Components.Component.Releases.Release.Description();
    }

    /**
     * Create an instance of {@link Components.Component.Screenshots.Screenshot.Caption }
     * 
     */
    public Components.Component.Screenshots.Screenshot.Caption createComponentsComponentScreenshotsScreenshotCaption() {
        return new Components.Component.Screenshots.Screenshot.Caption();
    }

    /**
     * Create an instance of {@link Components.Component.Screenshots.Screenshot.Image }
     * 
     */
    public Components.Component.Screenshots.Screenshot.Image createComponentsComponentScreenshotsScreenshotImage() {
        return new Components.Component.Screenshots.Screenshot.Image();
    }

    /**
     * Create an instance of {@link Components.Component.Keywords.Keyword }
     * 
     */
    public Components.Component.Keywords.Keyword createComponentsComponentKeywordsKeyword() {
        return new Components.Component.Keywords.Keyword();
    }

    /**
     * Create an instance of {@link Components.Component.Description.Ul }
     * 
     */
    public Components.Component.Description.Ul createComponentsComponentDescriptionUl() {
        return new Components.Component.Description.Ul();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "li", scope = Components.Component.Description.Ul.class)
    public JAXBElement<String> createComponentsComponentDescriptionUlLi(String value) {
        return new JAXBElement<String>(_ComponentsComponentDescriptionUlLi_QNAME, String.class, Components.Component.Description.Ul.class, value);
    }

}
